version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pimobile:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=pimobile
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres